name : CI

on:
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Descargando el proyecto
      - uses: actions/checkout@v3
      - name: Instalando mi java
